import AuthProtected from "@/components/auth/AuthProtected";
import CaseList from "@/components/cases/CaseList";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Módulo Seguimiento FALP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProtected>
        <CaseList />
      </AuthProtected>
    </>
  );
}
